version: "3"

services:
  postgres:
    container_name: postgres_database
    image: postgres
    environment:
      POSTGRES_USER: gurpreet
      POSTGRES_PASSWORD: gurpreet
      POSTGRES_DB: ImagesDatabase
      PGDATA: /data/postgres
      
    volumes:
       - mydb:/data/postgres
    networks: 
       - admin
    ports:
      - "9811:5432"
    restart: always
  
  web: 
    container_name : webapp
    build: .
    environment:
      DBHOST: postgres_database
      DBNAME: ImagesDatabase
      DBUSER: "gurpreet"
      DBPASS: "gurpreet"
    networks :
      - admin
    ports:
      - "9000:5000"
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: imailgurpreet@gmail.com
      PGADMIN_DEFAULT_PASSWORD: gurpreet
    networks : 
      - admin
    ports:
      - "8007:80"
    restart: always

networks:
  admin:
    driver: bridge

volumes :
  mydb:
